### ISSUE TITLE
Product Variations Not Working?

### ISSUE THREAD

**Issue by sgerritse** [MastermindMedia/HavensCreamery#2]
On this page: http://havenscreamery.com/shop/cakes/ice-cream-cake/

It keeps telling me "Sorry, no products matched your selection. Please choose a different combination." however, if you check the "Global Add-on's" (Products - Global Add-on's)

You will see that I have the variations set for any products in the category "Cakes". 

Using this plugin: https://woocommerce.com/products/product-add-ons/

**Comment by nitubasra** [comment]
FYI: I have worked on style.css under the food-drop-child theme. I have not worked on any core files so I am not pushing any code to github. 

Here are the updates: 
----------------------
I have access the wp and fix the issue related to the variations. The reason is incorrect setup of product variations.
